### ISSUE TITLE
Add pre-commit hooks for tests

### ISSUE THREAD

**Issue by zerodom30** [zerodom30/node-rsi#2]
Add pre-commit hooks for tests to run before new commits are added.

**Comment by BeniCheni** [comment]
@zerodom30 , here you go: #3

**Comment by BeniCheni** [comment]
Oh nice. @zerodom30  🙏 & 👍 for taking the PR.  Can you close this related issue as well?

(I don't have any edit access to your repo yet. May need collaborator close out issue for you. Or you would need to run the validate of issue and manage the closing for now without giving out collaborator access)

**Comment by zerodom30** [comment]
@BeniCheni marking this as closed per your last 2 PRs.
