### ISSUE TITLE
Create a reference on README to suggest emoji prefix in commit message?

### ISSUE THREAD

**Issue by BeniCheni** [zerodom30/node-rsi#5]
@zerodom30 
Found emoji prefixes with commit messages would have nice looking integrated icons with PRs and commit history. Do you think we can highlight the this emoji reference:
https://github.com/dannyfritz/commit-message-emoji

**Comment by zerodom30** [comment]
I like that idea, go ahead with it.

**Comment by BeniCheni** [comment]
Closing issue per merging of #6 . 🎊 🙏 @zerodom30
